services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    volumes:
      - consul_data:/consul/data  # Wolumen dla danych trwałych Consul
      - ./consul/server.json:/consul/config/server.json
    ports:
      - "8500:8500"  # Consul UI i API
      - "8600:8600/udp"  # DNS
    command: >
      consul agent -server -bootstrap -ui -client=0.0.0.0
      -data-dir=/consul/data
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "datacenter": "dc1",
          "primary_datacenter": "dc1",
          "connect": { "enabled": true }
        }
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port komunikacyjny RabbitMQ
      - "15672:15672"  # Port interfejsu zarządzania
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - consul
    environment:
      - CONSUL_SERVER=http://consul-server:8500

  registration_service:
    build: 
      context: ../services/registration_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - CONSUL_SERVER=http://consul-server:8500
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  product_service:
    build: 
      context: ../services/product_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - app-network
    depends_on:
      - consul
    environment:
      - CONSUL_SERVER=http://consul-server:8500

  orders_service:
    build: 
      context: ../services/orders_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      - app-network
    depends_on:
      - consul
    environment:
      - CONSUL_SERVER=http://consul-server:8500

  rating_service:
    build:
      context: ../services/rating_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    networks:
      - app-network
    depends_on:
      - consul
    environment:
      - CONSUL_SERVER=http://consul-server:8500

  notification_service:
    build:
      context: ../services/notification_service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    networks:
      - app-network
    depends_on:
      - consul
      - rabbitmq
    environment:
      - CONSUL_SERVER=http://consul-server:8500
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.endpoint.address=consul-server:8500"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - consul
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml

volumes:
  consul_data:

networks:
  app-network:
    driver: bridge
