version: "3.9"
services:
  orders_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"  # Mapowanie portów
    environment:
      - SECRET_KEY=your_secret_key
      - DATABASE_URI=sqlite:///orders_service.db  # Lokalna baza SQLite
    volumes:
      - ./instance:/app/instance  # Montowanie danych bazy
    restart: always
