api:
  insecure: true # Udostępnia panel Traefika (Tylko do testów!)
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  consulCatalog:
    defaultRule: "Host(`{{ .Name }}.localhost`)"
    exposedByDefault: true
    endpoint:
      address: "consul-server:8500"
      scheme: http

log:
  level: DEBUG
